version: '3.1'

networks:
  app-tier:
    driver: bridge

services:
  web:
    networks:
      - app-tier
    build: .
    volumes:
      - ./:/app
      - ./docker-entrypoint.sh:/app/docker-entrypoint.sh
      - /app/src/node_modules
    restart: always
    ports:
      - "8000:8000"
    links:
      - mysql
    depends_on:
      - mysql
      
  mysql:
    networks:
      - app-tier
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: bisc
      MYSQL_USER: challange
      MYSQL_PASSWORD: "aa"
      MYSQL_ROOT_PASSWORD: "bb"
    